Resources:
  ConversationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${param:API_NAME}-${aws:region}-${aws:accountId}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
        - AttributeName: message_id
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
        - AttributeName: message_id
          KeyType: RANGE
